### ISSUE TITLE
Mods the Server

### ISSUE THREAD

**Issue by aisaya-ana** [Hetsh/docker-starbound#3]
The image is nice to run the game without any login. I love it.
But you did not motion any about the mods. So I assume that you don't make this server assessable to the mods.
But not much problem for me to do, thank to your code, I can add one line to my docker-compose to allow me insert any mods to server. So next build, maybe you can add mods directory similar to "storage" that should be much easies
[docker-compose.yml.txt](https://github.com/Hetsh/docker-starbound/files/8684700/docker-compose.yml.txt)
.

**Comment by Hetsh** [comment]
Hi, I am glad you like the image :)

I hope I understood your request, but if I got it wrong, feel free to correct me. In my opinion, shipping the image with included mods would make it less attractive. Some people might want to play with different mods or no mods at all.

Instead, I think an additional section in the ReadMe which describes the modding-process would be appropriate. Since applying mods seems to be as easy as mounting them into the container, the section will be quite short too. What do you think?

**Comment by Hetsh** [comment]
Closed due to inactivity...

**Comment by spannerman79** [comment]
To prevent unnedded issues being opened up, what is the internal mount point that points towards `/path/to/server/mods` ?

I'll be using docker-compose so its pretty easy to define a mount point in compose.

ie: 
```yaml
volumes:
      - `/host/mount/mods:/path/to/server/mods`
```
